---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: true
  trailing-spaces: enable
  document-start:
    present: true
  comments:
    min-spaces-from-content: 1