---
extends: default
rules:
  # Disable line length enforcement for YAML files
  line-length: disable

  # Disable final newline requirement
  new-line-at-end-of-file: disable

  # Disable style-only rules that don't improve code quality
  document-start: disable
  truthy: disable
  brackets: disable

  # Keep other useful rules active
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  trailing-spaces: enable