---
# Default configuration values
# These values will be used if not specified in environment variables

defaults:
  # Instance naming
  instance_display_name: "oci-free-instance"

  # Network configuration
  assign_public_ip: false
  assign_private_dns_record: true

  # Retry configuration
  max_launch_attempts: 3
  retry_delay_seconds: 5

  # Notification configuration
  enable_notifications: true
  notification_retry_attempts: 3

  # Logging
  enable_debug_logging: false
  log_level: "info"  # debug, info, warning, error

  # OCI CLI configuration
  suppress_file_permissions_warning: true

  # Capacity handling
  capacity_error_is_failure: false  # Don't fail workflow on capacity errors
  capacity_retry_message: >
    No capacity available for shape at this time.
    Will retry on next schedule.

# Validation rules
validation:
  # Required environment variables
  required_secrets:
    - "OCI_USER_OCID"
    - "OCI_KEY_FINGERPRINT"
    - "OCI_TENANCY_OCID"
    - "OCI_REGION"
    - "OCI_PRIVATE_KEY"
    - "OCI_SUBNET_ID"
    - "INSTANCE_SSH_PUBLIC_KEY"
    - "TELEGRAM_TOKEN"
    - "TELEGRAM_USER_ID"

  # Optional environment variables (will use defaults if not provided)
  optional_secrets:
    - "OCI_COMPARTMENT_ID"  # Defaults to tenancy OCID
    - "OCI_IMAGE_ID"        # Auto-discovered if not provided

  # OCID format patterns
  ocid_patterns:
    user: "^ocid1\\.user\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"
    tenancy: "^ocid1\\.tenancy\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"
    compartment: "^ocid1\\.compartment\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"
    subnet: "^ocid1\\.subnet\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"
    image: "^ocid1\\.image\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"
    instance: "^ocid1\\.instance\\.[a-z0-9-]*\\.[a-z0-9-]*\\..+"

  # Shape-specific validation
  flexible_shapes:
    - "VM.Standard.A1.Flex"
    - "VM.Standard.E3.Flex"
    - "VM.Standard.E4.Flex"

  # Resource limits for free tier
  free_tier_limits:
    arm_instances: 4
    amd_instances: 2
    max_ocpus_arm: 4
    max_memory_gb_arm: 24
    max_ocpus_amd: 1
    max_memory_gb_amd: 1
