---
# Instance configuration profiles
# This file defines different instance configurations that can be used

profiles:
  # Default ARM instance (current configuration)
  arm-singapore:
    description: "ARM-based instance in Singapore"
    region: "ap-singapore-1"
    availability_domain: "fgaj:AP-SINGAPORE-1-AD-1"
    shape: "VM.Standard.A1.Flex"
    ocpus: 4
    memory_gb: 24
    operating_system: "Oracle Linux"
    os_version: "10"
    assign_public_ip: false

  # Alternative AMD instance
  amd-singapore:
    description: "AMD-based micro instance in Singapore"
    region: "ap-singapore-1"
    availability_domain: "fgaj:AP-SINGAPORE-1-AD-1"
    shape: "VM.Standard.E2.1.Micro"
    operating_system: "Oracle Linux"
    os_version: "10"
    assign_public_ip: false

  # ARM instance with public IP
  arm-singapore-public:
    description: "ARM-based instance in Singapore with public IP"
    region: "ap-singapore-1"
    availability_domain: "fgaj:AP-SINGAPORE-1-AD-1"
    shape: "VM.Standard.A1.Flex"
    ocpus: 2
    memory_gb: 12
    operating_system: "Oracle Linux"
    os_version: "10"
    assign_public_ip: true

  # Frankfurt region alternative
  arm-frankfurt:
    description: "ARM-based instance in Frankfurt"
    region: "eu-frankfurt-1"
    availability_domain: "FeVO:EU-FRANKFURT-1-AD-2"
    shape: "VM.Standard.A1.Flex"
    ocpus: 4
    memory_gb: 24
    operating_system: "Oracle Linux"
    os_version: "10"
    assign_public_ip: false

  # Ubuntu instance
  arm-ubuntu:
    description: "ARM-based Ubuntu instance"
    region: "ap-singapore-1"
    availability_domain: "fgaj:AP-SINGAPORE-1-AD-1"
    shape: "VM.Standard.A1.Flex"
    ocpus: 4
    memory_gb: 24
    operating_system: "Canonical Ubuntu"
    os_version: "24.04"
    assign_public_ip: false

# Default profile to use if none specified
default_profile: "arm-singapore"
