---
# Oracle Cloud regions and availability domains
# Reference configuration for different OCI regions

regions:
  # Asia Pacific regions
  ap-singapore-1:
    name: "Asia Pacific (Singapore)"
    availability_domains:
      - "fgaj:AP-SINGAPORE-1-AD-1"
    free_tier_available: true

  ap-sydney-1:
    name: "Asia Pacific (Sydney)"
    availability_domains:
      - "TvRS:AP-SYDNEY-1-AD-1"
    free_tier_available: true

  ap-tokyo-1:
    name: "Asia Pacific (Tokyo)"
    availability_domains:
      - "KQVh:AP-TOKYO-1-AD-1"
    free_tier_available: true

  ap-mumbai-1:
    name: "Asia Pacific (Mumbai)"
    availability_domains:
      - "TFmX:AP-MUMBAI-1-AD-1"
    free_tier_available: true

  ap-seoul-1:
    name: "Asia Pacific (Seoul)"
    availability_domains:
      - "nfYH:AP-SEOUL-1-AD-1"
    free_tier_available: true

  # Europe regions
  eu-frankfurt-1:
    name: "Europe (Frankfurt)"
    availability_domains:
      - "FeVO:EU-FRANKFURT-1-AD-1"
      - "FeVO:EU-FRANKFURT-1-AD-2"
      - "FeVO:EU-FRANKFURT-1-AD-3"
    free_tier_available: true

  eu-amsterdam-1:
    name: "Europe (Amsterdam)"
    availability_domains:
      - "EMib:EU-AMSTERDAM-1-AD-1"
    free_tier_available: true

  uk-london-1:
    name: "UK South (London)"
    availability_domains:
      - "jbkU:UK-LONDON-1-AD-1"
      - "jbkU:UK-LONDON-1-AD-2"
      - "jbkU:UK-LONDON-1-AD-3"
    free_tier_available: true

  # North America regions
  us-ashburn-1:
    name: "US East (Ashburn)"
    availability_domains:
      - "oGHu:US-ASHBURN-1-AD-1"
      - "oGHu:US-ASHBURN-1-AD-2"
      - "oGHu:US-ASHBURN-1-AD-3"
    free_tier_available: true

  us-phoenix-1:
    name: "US West (Phoenix)"
    availability_domains:
      - "EMTh:US-PHOENIX-1-AD-1"
      - "EMTh:US-PHOENIX-1-AD-2"
      - "EMTh:US-PHOENIX-1-AD-3"
    free_tier_available: true

  ca-toronto-1:
    name: "Canada Southeast (Toronto)"
    availability_domains:
      - "YnyK:CA-TORONTO-1-AD-1"
    free_tier_available: true

  # South America regions
  sa-saopaulo-1:
    name: "South America (São Paulo)"
    availability_domains:
      - "GGaP:SA-SAOPAULO-1-AD-1"
    free_tier_available: true

# Common shapes available in free tier
free_tier_shapes:
  arm:
    - "VM.Standard.A1.Flex"
  amd:
    - "VM.Standard.E2.1.Micro"

# Operating systems commonly available
operating_systems:
  oracle_linux:
    name: "Oracle Linux"
    versions: ["8", "9"]
    default_version: "9"
  ubuntu:
    name: "Canonical Ubuntu"
    versions: ["20.04", "22.04"]
    default_version: "22.04"
  centos:
    name: "CentOS"
    versions: ["7", "8"]
    default_version: "8"
