# Oracle Free Tier Configuration Template - Singapore (ARM)
# Copy to your GitHub Actions workflow environment variables

# Region and Availability Domain
OCI_REGION: "ap-singapore-1"
OCI_AD: "fgaj:AP-SINGAPORE-1-AD-1,fgaj:AP-SINGAPORE-1-AD-2"

# Instance Configuration
OCI_SHAPE: "VM.Standard.A1.Flex"
OCI_OCPUS: "4"                    # Max 4 OCPUs for free tier
OCI_MEMORY_IN_GBS: "24"          # Max 24 GB RAM for free tier
INSTANCE_DISPLAY_NAME: "free-tier-arm-sg"
ASSIGN_PUBLIC_IP: "false"        # Set to "true" if you need public access

# Operating System
OPERATING_SYSTEM: "Oracle Linux"
OS_VERSION: "10"

# Boot Volume Configuration
BOOT_VOLUME_SIZE: "50"           # Minimum 50 GB (max 200 GB for free tier)

# Instance Recovery and Compatibility
RECOVERY_ACTION: "RESTORE_INSTANCE"
LEGACY_IMDS_ENDPOINTS: "false"

# Multi-AD Retry Configuration
RETRY_WAIT_TIME: "30"            # Seconds between AD attempts

# Instance Verification Timeout
INSTANCE_VERIFY_MAX_CHECKS: "5"
INSTANCE_VERIFY_DELAY: "30"

# Logging Configuration
LOG_FORMAT: "text"               # or "json" for structured logging

# ARM Image Cache (Update periodically)
# Check latest ARM images: oci compute image list --compartment-id <tenancy-ocid> --operating-system "Oracle Linux" --operating-system-version "10" --shape "VM.Standard.A1.Flex" --sort-by TIMECREATED --sort-order DESC
OCI_CACHED_OL10_ARM_IMAGE: "ocid1.image.oc1.ap-singapore-1.aaaaaaaay4vc5rcekxthq7cillis3qred5xyz7kmqd6wuaoknk4zukohqlua"

# Required GitHub Secrets (not environment variables):
# OCI_USER_OCID: Your OCI user OCID
# OCI_KEY_FINGERPRINT: Your API key fingerprint  
# OCI_TENANCY_OCID: Your tenancy OCID
# OCI_PRIVATE_KEY: Your private API key content
# OCI_COMPARTMENT_ID: Target compartment OCID
# OCI_SUBNET_ID: Target subnet OCID
# INSTANCE_SSH_PUBLIC_KEY: SSH public key for instance access
# TELEGRAM_TOKEN: Telegram bot token
# TELEGRAM_USER_ID: Your Telegram user ID

# Notes:
# - ARM instances (A1.Flex) are more readily available than AMD in most regions
# - Multi-AD configuration significantly improves success rates
# - Free tier limits: 4 OCPUs, 24 GB RAM, 200 GB boot volume per tenancy
# - Singapore region generally has good availability for free tier resources
