name: Claude Automatic Mode Detection

on:
  # Events for interactive mode (responds to @claude mentions)
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  # Events for automation mode (runs with explicit prompt)
  workflow_dispatch:
  schedule:
    - cron: "55 */5 * * *" # At the end of the hour, every 5 hours

jobs:
  interactive-mode:
    # if: |
    #   (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && !contains(github.event.comment.body, '@claude reviewer')) ||
    #   (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
    #   (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
    #   (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    if: |
      ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }} &&
      !contains(github.event.comment.body, '@claude reviewer')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - uses: anthropics/claude-code-action@v1-dev
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          # Interactive mode (auto-detected when no prompt):
          # - Scans for @claude mentions in comments, issues, and PRs
          # - Only acts when trigger phrase is found
          # - Creates tracking comments with progress checkboxes
          # - Perfect for: Interactive Q&A, on-demand code changes
            
  # Automation Mode - Activated automatically when prompt is provided
  automation-mode-scheduled-task:
    if: |
      ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: anthropics/claude-code-action@v1-dev
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Check for outdated dependencies and security vulnerabilities.
            Create an issue if any critical problems are found.
          # Automation mode (auto-detected when prompt provided):
          # - Works with any GitHub event
          # - Executes immediately without waiting for @claude mentions
          # - No tracking comments created
          # - Perfect for: scheduled maintenance, automated reviews, CI/CD tasks
